### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by ggilder** [zizkovrb/melt#2]
```
➤ gem install melt
Fetching: melt-0.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing melt:
        ERROR: Failed to build gem native extension.

    /Users/gabriel/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150226-30878-117rd0t.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling melt.c
melt.c:1:10: fatal error: 'melt.h' file not found
#include "melt.h"
         ^
1 error generated.
make: *** [melt.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/gabriel/.rvm/gems/ruby-2.2.0/gems/melt-0.2 for inspection.
Results logged to /Users/gabriel/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-13/2.2.0/melt-0.2/gem_make.out
```

Any ideas?

**Comment by simi** [comment]
Hmm, are you able to compile another native gems like Nokogiri?

**Comment by tom-lord** [comment]
I think this is a trivial bug, which you introduced here: https://github.com/zizkovrb/melt/commit/be97968d9e7c171426faf220b8dd4f93492b42b3#diff-54c7e3ece1a10a2a325ca83af1f89e9cR20

You are not including the header file (`fatal error: 'melt.h' file not found`) in the gemspec files! I've fixed this in a pull request :)

**Comment by simi** [comment]
@ggilder I just released 0.3. Can try to reproduce this with `gem install melt --version 0.3`?

**Comment by ggilder** [comment]
Works now! Thanks :)

**Comment by simi** [comment]
Thank belongs to @tom-lord!
